### ISSUE TITLE
Understanding of the repo

### ISSUE THREAD

**Issue by kr-sundaram** [MTEnglish2Odia/NMT#1]
Hi, Thanks for making this repo public.

I am new to machine translation and i would like to use your repo for my dataset but not sure where to start.

Could you please let me know the steps to follow for having my models trained and get the new sentence translated.

**Comment by subhadarship** [comment]
Thanks for the question! This [notebook](https://github.com/MTEnglish2Odia/NMT/blob/master/nmt/attention_is_all_you_need_en_od.ipynb) is a good place to start, or more generally, notebooks in this [repo](https://github.com/bentrevett/pytorch-seq2seq).
